#pragma once

enum TColor {

    // FG
    FG_BLACK,
    FG_DARK_RED,
    FG_DARK_GREEN,
    FG_DARK_YELLOW,
    FG_DARK_BLUE,
    FG_DARK_MAGENTA,
    FG_DARK_CYAN,
    FG_DARK_GRAY,
    FG_LIGHT_GRAY,
    FG_BRIGHT_RED,
    FG_BRIGHT_GREEN,
    FG_BRIGHT_YELLOW,
    FG_BRIGHT_BLUE,
    FG_BRIGHT_MAGENTA,
    FG_BRIGHT_CYAN,
    FG_WHITE,
    // BG
    BG_BLACK,
    BG_DARK_RED,
    BG_DARK_GREEN,
    BG_DARK_YELLOW,
    BG_DARK_BLUE,
    BG_DARK_MAGENTA,
    BG_DARK_CYAN,
    BG_DARK_GRAY,
    BG_LIGHT_GRAY,
    BG_BRIGHT_RED,
    BG_BRIGHT_GREEN,
    BG_BRIGHT_YELLOW,
    BG_BRIGHT_BLUE,
    BG_BRIGHT_MAGENTA,
    BG_BRIGHT_CYAN,
    BG_WHITE,


    // SPECIAL
    RESET, 
    BOLD, 
    UNDERLINE,
    NO_UNDERLINE,
    REVERSE_TEXT,
    POSITIVE_TEXT

};

const char* set_color(TColor color);


